import {StyleSheet} from 'react-native';
import {FONTS} from '../screen/assets';
export default StyleSheet.create({
  wrapperContainer: {backgroundColor: 'white', flex: 1},
  companyLogo: {alignItems: 'center'},
  companyImage: {width: 226, height: 64, marginTop: 72},
  firstContainer: {
    width: '80%',
    height: 138,
    borderWidth: 1,
    borderColor: '#4A96C6',
    backgroundColor: '#FFF',
    borderRadius: 20,
    shadowColor: '#000',
    elevation: 5,
    marginTop: 200,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    position: 'relative',
  },
  firstImage: {
    width: 84,
    height: 84,
    marginTop: 27,
    marginLeft: 27,
    marginBottom: 27,
  },
  firstText: {
    fontSize: 27,
    fontWeight: '400',
    ...FONTS.h2,
    color: '#000',
    marginTop: 49,
    marginBottom: 51,
    marginRight: 20,
  },
  secondContainer: {
    width: '80%',
    height: 138,
    borderWidth: 1,
    borderColor: '#4A96C6',
    backgroundColor: '#FFF',
    borderRadius: 20,
    shadowColor: '#000',
    elevation: 5,
    marginTop: 45,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    position: 'relative',
  },
  secondImage: {
    width: 84,
    height: 84,
    marginTop: 27,
    marginLeft: 27,
    marginBottom: 27,
  },
  secondText: {
    fontSize: 27,
    fontWeight: '400',
    ...FONTS.h2,
    color: '#000',
    marginTop: 49,
    marginRight: 20,
    marginBottom: 51,
  },
  thirdContainer: {
    width: '80%',
    height: 138,
    borderWidth: 1,
    borderColor: '#4A96C6',
    backgroundColor: '#FFF',
    borderRadius: 20,
    shadowColor: '#000',
    elevation: 5,
    marginTop: 45,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignSelf: 'center',
    position: 'relative',
    marginBottom:195
  },
  thirdImage: {width:95,height:95,marginLeft:26,marginTop:21,marginBottom:22},
 
});
