import {StyleSheet} from 'react-native';
import {FONTS} from '../screen/assets';
export default StyleSheet.create({
  mainContainer: {backgroundColor: '#fff', flex: 1},
  companyImage: {alignItems: 'center'},
  companylogo: {width: 226, height: 64, marginTop: 72},
  first: {
    width: '80%',
    height: 150,
    borderWidth: 1,
    borderColor: '#0082B9',
    shadowColor: '#000',
    elevation: 10,
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: 17,
    position: 'relative',
    alignSelf: 'center',
  },
  heading: {
    width: '100%',
    height: 34,
    backgroundColor: '#77D85E',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    position: 'absolute',
    top: 0,
    shadowColor: '#000',
    elevation: 10,
  },
  headingtitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginTop: 8,
  },
  brandImageFirst: {width: 65, height: 82, top: 52, left: 10},
  colbox: {
    flexDirection: 'row',
    position: 'absolute',
    top: 50,
    left: 80,
    justifyContent: 'space-around',
  },
  colfirst: {
    width: '100%',
    height: 33,
    backgroundColor: '#77D85E',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
  },
  colsecond: {
    width: 58,
    height: 40,
    borderWidth: 1,
    borderColor: '#C6C6C6',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  colfirsttext: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginTop: 8,
  },
  colsecondtext: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0082B9',
    textAlign: 'center',
    marginTop: 9,
  },
  last: {
    width: '80%',
    height: 89,
    borderWidth: 1,
    borderColor: '#C6C6C6',
    alignSelf: 'center',
    marginTop: 18,
    borderRadius: 20,
    position: 'relative',
    shadowColor: 'black',
    elevation: 10,
    backgroundColor: '#fff',
  },
  remark: {
    width: 109,
    height: 28,
    backgroundColor: '#77D85E',
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  submitbtn: {
    width: '30%',
    height: 30,
    backgroundColor: '#77D85E',
    alignSelf: 'center',
    marginTop: 27,
    borderRadius: 5,
    marginBottom: 22,
  },
  brandImageSecond: {width: 50, height: 99, top: 46, left: 10},
  brandImageThird: {width: 41, height: 95, top: 46, left: 10},
  floorStockTitle: {
    marginTop: 19,
    height:35,
    flexDirection: 'row',
    alignSelf: 'center',
  },
  inventoryStyle: {width: 30, height: 30},
});
